HANDSHAKE_PROTOCOL = "json"
HANDSHAKE_VERSION = 1

JSON_RECORD_SEPARATOR = '\x1E'

INVOCATION_MESSAGE_TYPE = 1
STREAM_ITEM_MESSAGE_TYPE = 2
COMPLETION_MESSAGE_TYPE = 3
STREAM_INVOCATION_MESSAGE_TYPE = 4
CANCEL_INVOCATION_MESSAGE_TYPE = 5
PING_MESSAGE_TYPE = 6
CLOSE_MESSAGE_TYPE = 7